<?php

namespace Angle\ECF\Catalog;

use Angle\ECF\Catalog\Province;
use RuntimeException;


abstract class Municipality
{
    const MUN_SANTO_DOMINGO_DE_GUZMAN = '010100';
    const DM_SANTO_DOMINGO_DE_GUZMAN = '010101';
    const MUN_AZUA = '020100';
    const DM_AZUA = '020101';
    const DM_BARRO_ARRIBA = '020102';
    const DM_LAS_BARIAS_LA_ESTANCIA = '020103';
    const DM_LOS_JOVILLOS = '020104';
    const DM_PUERTO_VIEJO = '020105';
    const DM_BARRERAS = '020106';
    const DM_DONA_EMMA_BALAGUER_VIUDA_VALLEJO = '020107';
    const DM_CLAVELLINA = '020108';
    const DM_LAS_LOMAS = '020109';
    const MUN_LAS_CHARCAS = '020200';
    const DM_LAS_CHARCAS = '020201';
    const DM_PALMAR_DE_OCOA = '020202';
    const MUN_LAS_YAYAS_DE_VIAJAMA = '020300';
    const DM_LAS_YAYAS_DE_VIAJAMA = '020301';
    const DM_VILLARPANDO = '020302';
    const DM_HATO_NUEVO_CORTES = '020303';
    const MUN_PADRE_LAS_CASAS = '020400';
    const DM_PADRE_LAS_CASAS = '020401';
    const DM_LAS_LAGUNAS_AZUA = '020402';
    const DM_LA_SIEMBRA = '020403';
    const DM_MONTE_BONITO = '020404';
    const DM_LOS_FRIOS = '020405';
    const MUN_PERALTA = '020500';
    const DM_PERALTA = '020501';
    const MUN_SABANA_YEGUA = '020600';
    const DM_SABANA_YEGUA = '020601';
    const DM_PROYECTO_4 = '020602';
    const DM_GANADERO = '020603';
    const DM_PROYECTO_2_C = '020604';
    const MUN_PUEBLO_VIEJO = '020700';
    const DM_PUEBLO_VIEJO = '020701';
    const DM_EL_ROSARIO_AZUA = '020702';
    const MUN_TABARA_ARRIBA = '020800';
    const DM_TABARA_ARRIBA = '020801';
    const DM_TABARA_ABAJO = '020802';
    const DM_AMIAMA_GOMEZ = '020803';
    const DM_LOS_TOROS = '020804';
    const MUN_GUAYABAL_AZUA = '020900';
    const DM_GUAYABAL_AZUA = '020901';
    const MUN_ESTEBANIA = '021000';
    const DM_ESTEBANIA = '021001';
    const MUN_NEIBA = '030001';
    const DM_NEIBA = '030101';
    const DM_EL_PALMAR = '030102';
    const MUN_GALVAN = '030200';
    const DM_GALVAN = '030201';
    const DM_EL_SALADO = '030202';
    const MUN_TAMAYO = '030300';
    const DM_TAMAYO = '030301';
    const DM_UVILLA = '030302';
    const DM_SANTANA_BAHORUCO = '030303';
    const DM_MONSERRATE = '030304';
    const DM_CABEZA_DE_TORO = '030305';
    const DM_MENA = '030306';
    const DM_SANTA_BARBARA_EL_6 = '030307';
    const MUN_VILLA_JARAGUA = '030400';
    const DM_VILLA_JARAGUA = '030401';
    const MUN_LOS_RIOS = '030500';
    const DM_LOS_RIOS = '030501';
    const DM_LAS_CLAVELLINAS_BAHORUCO = '030502';
    const MUN_BARAHONA = '040100';
    const DM_BARAHONA = '040101';
    const DM_EL_CACHON = '040102';
    const DM_LA_GUAZARA = '040103';
    const DM_VILLA_CENTRAL = '040104';
    const MUN_CABRAL = '040200';
    const DM_CABRAL = '040201';
    const MUN_ENRIQUILLO = '040300';
    const DM_ENRIQUILLO = '040301';
    const DM_ARROYO_DULCE = '040302';
    const MUN_PARAISO = '040400';
    const DM_PARAISO = '040401';
    const DM_LOS_PATOS = '040402';
    const MUN_VICENTE_NOBLE = '040500';
    const DM_VICENTE_NOBLE = '040501';
    const DM_CANOA = '040502';
    const DM_QUITA_CORAZA = '040503';
    const DM_FONDO_NEGRO = '040504';
    const MUN_EL_PENON = '040600';
    const DM_EL_PENON = '040601';
    const MUN_LA_CIENAGA_BARAHONA = '040700';
    const DM_LA_CIENAGA_BARAHONA = '040701';
    const DM_BAHORUCO = '040702';
    const MUN_FUNDACION = '040800';
    const DM_FUNDACION = '040801';
    const DM_PESCADERIA = '040802';
    const MUN_LAS_SALINAS = '040900';
    const DM_LAS_SALINAS = '040901';
    const MUN_POLO = '041000';
    const DM_POLO = '041001';
    const MUN_JAQUIMEYES = '041100';
    const DM_JAQUIMEYES = '041101';
    const DM_PALO_ALTO = '041102';
    const MUN_DAJABON = '050100';
    const DM_DAJABON = '050101';
    const DM_CANONGO = '050102';
    const MUN_LOMA_DE_CABRERA = '050200';
    const DM_LOMA_DE_CABRERA = '050201';
    const DM_CAPOTILLO = '050202';
    const DM_SANTIAGO_DE_LA_CRUZ = '050203';
    const MUN_PARTIDO = '050300';
    const DM_PARTIDO = '050301';
    const MUN_RESTAURACION = '050400';
    const DM_RESTAURACION = '050401';
    const MUN_EL_PINO = '050500';
    const DM_EL_PINO = '050501';
    const DM_MANUEL_BUENO = '050502';
    const MUN_SAN_FRANCISCO_DE_MACORIS = '060100';
    const DM_SAN_FRANCISCO_DE_MACORIS = '060101';
    const DM_LA_PENA = '060102';
    const DM_CENOVI = '060103';
    const DM_JAYA = '060104';
    const DM_PRESIDENTE_DON_ANTONIO_GUZMAN_FERNANDEZ = '060105';
    const MUN_ARENOSO = '060200';
    const DM_ARENOSO = '060201';
    const DM_LAS_COLES = '060202';
    const DM_EL_AGUACATE = '060203';
    const MUN_CASTILLO = '060300';
    const DM_CASTILLO = '060301';
    const MUN_PIMENTEL = '060400';
    const DM_PIMENTEL = '060401';
    const MUN_VILLA_RIVA = '060500';
    const DM_VILLA_RIVA = '060501';
    const DM_AGUA_SANTA_DEL_YUNA = '060502';
    const DM_CRISTO_REY_DE_GUARAGUAO = '060503';
    const DM_LAS_TARANAS = '060504';
    const DM_BARRAQUITO = '060505';
    const MUN_LAS_GUARANAS = '060600';
    const DM_LAS_GUARANAS = '060601';
    const MUN_EUGENIO_MARIA_DE_HOSTOS = '060700';
    const DM_EUGENIO_MARIA_DE_HOSTOS = '060701';
    const DM_SABANA_GRANDE_DUARTE = '060702';
    const MUN_COMENDADOR = '070100';
    const DM_COMENDADOR = '070101';
    const DM_SABANA_LARGA_ELIAS_PINA = '070102';
    const DM_GUAYABO = '070103';
    const MUN_BANICA = '070200';
    const DM_BANICA = '070201';
    const DM_SABANA_CRUZ = '070202';
    const DM_SABANA_HIGUERO = '070203';
    const MUN_EL_LLANO = '070300';
    const DM_EL_LLANO = '070301';
    const DM_GUANITO_ELIAS_PINA = '070302';
    const MUN_HONDO_VALLE = '070400';
    const DM_HONDO_VALLE = '070401';
    const DM_RANCHO_DE_LA_GUARDIA = '070402';
    const MUN_PEDRO_SANTANA = '070500';
    const DM_PEDRO_SANTANA = '070501';
    const DM_RIO_LIMPIO = '070502';
    const MUN_JUAN_SANTIAGO = '070600';
    const DM_JUAN_SANTIAGO = '070601';
    const MUN_EL_SEIBO = '080100';
    const DM_EL_SEIBO = '080101';
    const DM_PEDRO_SANCHEZ = '080102';
    const DM_SAN_FRANCISCO_VICENTILLO = '080103';
    const DM_SANTA_LUCIA = '080104';
    const MUN_MICHES = '080200';
    const DM_MICHES = '080201';
    const DM_EL_CEDRO = '080202';
    const DM_LA_GINA = '080203';
    const MUN_MOCA = '090100';
    const DM_MOCA = '090101';
    const DM_JOSE_CONTRERAS = '090102';
    const DM_SAN_VICTOR = '090103';
    const DM_JUAN_LOPEZ = '090104';
    const DM_LAS_LAGUNAS_ESPAILLAT = '090105';
    const DM_CANCA_LA_REYNA = '090106';
    const DM_EL_HIGUERITO = '090107';
    const DM_MONTE_DE_LA_JAGUA = '090108';
    const DM_LA_ORTEGA = '090109';
    const MUN_CAYETANO_GERMOSEN = '090200';
    const DM_CAYETANO_GERMOSEN = '090201';
    const MUN_GASPAR_HERNANDEZ = '090300';
    const DM_GASPAR_HERNANDEZ = '090301';
    const DM_JOBA_ARRIBA = '090302';
    const DM_VERAGUA = '090303';
    const DM_VILLA_MAGANTE = '090304';
    const MUN_JAMAO_AL_NORTE = '090400';
    const DM_JAMAO_AL_NORTE = '090401';
    const MUN_JIMANI = '100100';
    const DM_JIMANI = '100101';
    const DM_EL_LIMON_INDEPENDENCIA = '100102';
    const DM_BOCA_DE_CACHON = '100103';
    const MUN_DUVERGE = '100200';
    const DM_DUVERGE = '100201';
    const DM_VENGAN_A_VER = '100202';
    const MUN_LA_DESCUBIERTA = '100300';
    const DM_LA_DESCUBIERTA = '100301';
    const MUN_POSTRER_RIO = '100400';
    const DM_POSTRER_RIO = '100401';
    const DM_GUAYABAL_INDEPENDENCIA = '100402';
    const MUN_CRISTOBAL = '100500';
    const DM_CRISTOBAL = '100501';
    const DM_BATEY_8 = '100502';
    const MUN_MELLA = '100600';
    const DM_MELLA = '100601';
    const DM_LA_COLONIA = '100602';
    const MUN_HIGUEY = '110100';
    const DM_HIGUEY = '110101';
    const DM_LAS_LAGUNAS_DE_NISIBON = '110102';
    const DM_LA_OTRA_BANDA = '110103';
    const DM_VERON_PUNTA_CANA = '110104';
    const MUN_SAN_RAFAEL_DEL_YUMA = '110200';
    const DM_SAN_RAFAEL_DEL_YUMA = '110201';
    const DM_BOCA_DE_YUMA = '110202';
    const DM_BAYAHIBE = '110203';
    const MUN_LA_ROMANA = '120100';
    const DM_LA_ROMANA = '120101';
    const DM_CALETA = '120102';
    const MUN_GUAYMATE = '120200';
    const DM_GUAYMATE = '120201';
    const MUN_VILLA_HERMOSA = '120300';
    const DM_VILLA_HERMOSA = '120301';
    const DM_CUMAYASA = '120302';
    const MUN_LA_VEGA = '130100';
    const DM_LA_VEGA = '130101';
    const DM_RIO_VERDE_ARRIBA = '130102';
    const DM_EL_RANCHITO = '130103';
    const DM_TAVERAS = '130104';
    const DM_DON_JUAN_RODRIGUEZ = '130105';
    const MUN_CONSTANZA = '130200';
    const DM_CONSTANZA = '130201';
    const DM_TIREO = '130202';
    const DM_LA_SABINA = '130203';
    const MUN_JARABACOA = '130300';
    const DM_JARABACOA = '130301';
    const DM_BUENA_VISTA = '130302';
    const DM_MANABAO = '130303';
    const MUN_JIMA_ABAJO = '130400';
    const DM_JIMA_ABAJO = '130401';
    const DM_RINCON = '130402';
    const MUN_NAGUA = '140100';
    const DM_NAGUA = '140101';
    const DM_SAN_JOSE_DE_MATANZAS = '140102';
    const DM_LAS_GORDAS = '140103';
    const DM_ARROYO_AL_MEDIO = '140104';
    const MUN_CABRERA = '140200';
    const DM_CABRERA = '140201';
    const DM_ARROYO_SALADO = '140202';
    const DM_LA_ENTRADA = '140203';
    const MUN_EL_FACTOR = '140300';
    const DM_EL_FACTOR = '140301';
    const DM_EL_POZO = '140302';
    const MUN_RIO_SAN_JUAN = '140400';
    const DM_RIO_SAN_JUAN = '140401';
    const MUN_MONTE_CRISTI = '150100';
    const DM_MONTE_CRISTI = '150101';
    const MUN_CASTANUELAS = '150200';
    const DM_CASTANUELAS = '150201';
    const DM_PALO_VERDE = '150202';
    const MUN_GUAYUBIN = '150300';
    const DM_GUAYUBIN = '150301';
    const DM_VILLA_ELISA = '150302';
    const DM_HATILLO_PALMA = '150303';
    const DM_CANA_CHAPETON = '150304';
    const MUN_LAS_MATAS_DE_SANTA_CRUZ = '150400';
    const DM_LAS_MATAS_DE_SANTA_CRUZ = '150401';
    const MUN_PEPILLO_SALCEDO = '150500';
    const DM_PEPILLO_SALCEDO_MANZANILLO = '150501';
    const DM_SANTA_MARIA = '150502';
    const MUN_VILLA_VASQUEZ = '150600';
    const DM_VILLA_VASQUEZ = '150601';
    const MUN_PEDERNALES = '160100';
    const DM_PEDERNALES = '160101';
    const DM_JOSE_FRANCISCO_PENA_GOMEZ = '160102';
    const MUN_OVIEDO = '160200';
    const DM_OVIEDO = '160201';
    const DM_JUANCHO = '160202';
    const MUN_BANI = '170100';
    const DM_BANI = '170101';
    const DM_MATANZAS_PERAVIA_1 = '170102';
    const DM_VILLA_FUNDACION = '170103';
    const DM_SABANA_BUEY = '170104';
    const DM_PAYA = '170105';
    const DM_VILLA_SOMBRERO = '170106';
    const DM_EL_CARRETON = '170107';
    const DM_CATALINA = '170108';
    const DM_EL_LIMONAL_PERAVIA = '170109';
    const DM_LAS_BARIAS_PERAVIA = '170110';
    const MUN_NIZAO = '170200';
    const DM_NIZAO = '170201';
    const DM_PIZARRETE = '170202';
    const DM_SANTANA_PERAVIA = '170203';
    const MUN_MATANZAS = '170300';
    const DM_MATANZAS_PERAVIA_2 = '170301';
    const MUN_PUERTO_PLATA = '180100';
    const DM_PUERTO_PLATA = '180101';
    const DM_YASICA_ARRIBA = '180102';
    const DM_MAIMON_PUERTO_PLATA = '180103';
    const MUN_ALTAMIRA = '180200';
    const DM_ALTAMIRA = '180201';
    const DM_RIO_GRANDE = '180202';
    const MUN_GUANANICO = '180300';
    const DM_GUANANICO = '180301';
    const MUN_IMBERT = '180400';
    const DM_IMBERT = '180401';
    const MUN_LOS_HIDALGOS = '180500';
    const DM_LOS_HIDALGOS = '180501';
    const DM_NAVAS = '180502';
    const MUN_LUPERON = '180600';
    const DM_LUPERON = '180601';
    const DM_LA_ISABELA = '180602';
    const DM_BELLOSO = '180603';
    const DM_EL_ESTRECHO_DE_LUPERON_OMAR_BROSS = '180604';
    const MUN_SOSUA = '180700';
    const DM_SOSUA = '180701';
    const DM_CABARETE = '180702';
    const DM_SABANETA_DE_YASICA = '180703';
    const MUN_VILLA_ISABELA = '180800';
    const DM_VILLA_ISABELA = '180801';
    const DM_ESTERO_HONDO = '180802';
    const DM_LA_JAIBA = '180803';
    const DM_GUALETE = '180804';
    const MUN_VILLA_MONTELLANO = '180900';
    const DM_VILLA_MONTELLANO = '180901';
    const MUN_SALCEDO = '190100';
    const DM_SALCEDO = '190101';
    const DM_JAMAO_AFUERA = '190102';
    const MUN_TENARES = '190200';
    const DM_TENARES = '190201';
    const DM_BLANCO = '190202';
    const MUN_VILLA_TAPIA = '190300';
    const DM_VILLA_TAPIA = '190301';
    const MUN_SAMANA = '200100';
    const DM_SAMANA = '200101';
    const DM_EL_LIMON_SAMANA = '200102';
    const DM_ARROYO_BARRIL = '200103';
    const DM_LAS_GALERAS = '200104';
    const MUN_SANCHEZ = '200200';
    const DM_SANCHEZ = '200201';
    const MUN_LAS_TERRENAS = '200300';
    const DM_LAS_TERRENAS = '200301';
    const MUN_SAN_CRISTOBAL = '210100';
    const DM_SAN_CRISTOBAL = '210101';
    const DM_HATO_DAMAS = '210102';
    const DM_HATILLO = '210103';
    const MUN_SABANA_GRANDE_DE_PALENQUE = '210200';
    const DM_SABANA_GRANDE_DE_PALENQUE = '210201';
    const MUN_BAJOS_DE_HAINA = '210300';
    const DM_BAJOS_DE_HAINA = '210301';
    const DM_EL_CARRIL = '210302';
    const DM_QUITA_SUENO_SAN_CRISTOBAL = '210303';
    const MUN_CAMBITA_GARABITOS = '210400';
    const DM_CAMBITA_GARABITOS = '210401';
    const DM_CAMBITA_EL_PUEBLECITO = '210402';
    const MUN_VILLA_ALTAGRACIA = '210500';
    const DM_VILLA_ALTAGRACIA = '210501';
    const DM_SAN_JOSE_DEL_PUERTO = '210502';
    const DM_MEDINA = '210503';
    const DM_LA_CUCHILLA = '210504';
    const MUN_YAGUATE = '210600';
    const DM_YAGUATE = '210601';
    const DM_DONA_ANA = '210602';
    const MUN_SAN_GREGORIO_DE_NIGUA = '210700';
    const DM_SAN_GREGORIO_DE_NIGUA = '210701';
    const MUN_LOS_CACAOS = '210800';
    const DM_LOS_CACAOS = '210801';
    const MUN_SAN_JUAN = '220100';
    const DM_SAN_JUAN = '220101';
    const DM_PEDRO_CORTO = '220102';
    const DM_SABANETA = '220103';
    const DM_SABANA_ALTA = '220104';
    const DM_EL_ROSARIO_SAN_JUAN = '220105';
    const DM_HATO_DEL_PADRE = '220106';
    const DM_GUANITO_SAN_JUAN = '220107';
    const DM_LA_JAGUA = '220108';
    const DM_LAS_MAGUANAS_HATO_NUEVO = '220109';
    const DM_LAS_CHARCAS_DE_MARIA_NOVA = '220110';
    const DM_LAS_ZANJAS = '220111';
    const MUN_BOHECHIO = '220200';
    const DM_BOHECHIO = '220201';
    const DM_ARROYO_CANO = '220202';
    const DM_YAQUE = '220203';
    const MUN_EL_CERCADO = '220300';
    const DM_EL_CERCADO = '220301';
    const DM_DERRUMBADERO = '220302';
    const DM_BATISTA = '220303';
    const MUN_JUAN_DE_HERRERA = '220400';
    const DM_JUAN_DE_HERRERA = '220401';
    const DM_JINOVA = '220402';
    const MUN_LAS_MATAS_DE_FARFAN = '220500';
    const DM_LAS_MATAS_DE_FARFAN = '220501';
    const DM_MATAYAYA = '220502';
    const DM_CARRERA_DE_YEGUAS = '220503';
    const MUN_VALLEJUELO = '220600';
    const DM_VALLEJUELO = '220601';
    const DM_JORJILLO = '220602';
    const MUN_SAN_PEDRO_DE_MACORIS = '230100';
    const DM_SAN_PEDRO_DE_MACORIS = '230101';
    const MUN_LOS_LLANOS = '230200';
    const DM_LOS_LLANOS = '230201';
    const DM_EL_PUERTO = '230202';
    const DM_GAUTIER = '230203';
    const MUN_RAMON_SANTANA = '230300';
    const DM_RAMON_SANTANA = '230301';
    const MUN_CONSUELO = '230400';
    const DM_CONSUELO = '230401';
    const MUN_QUISQUEYA = '230500';
    const DM_QUISQUEYA = '230501';
    const MUN_GUAYACANES = '230600';
    const DM_GUAYACANES = '230601';
    const MUN_COTUI = '240100';
    const DM_COTUI = '240101';
    const DM_QUITA_SUENO_SANCHEZ_RAMIREZ = '240102';
    const DM_CABALLERO = '240103';
    const DM_COMEDERO_ARRIBA = '240104';
    const DM_PLATANAL = '240105';
    const DM_ZAMBRANA_ABAJO = '240106';
    const MUN_CEVICOS = '240200';
    const DM_CEVICOS = '240201';
    const DM_LA_CUEVA = '240202';
    const MUN_FANTINO = '240300';
    const DM_FANTINO = '240301';
    const MUN_LA_MATA = '240400';
    const DM_LA_MATA = '240401';
    const DM_LA_BIJA = '240402';
    const DM_ANGELINA = '240403';
    const DM_HERNANDO_ALONZO = '240404';
    const MUN_SANTIAGO = '250100';
    const DM_SANTIAGO = '250101';
    const DM_PEDRO_GARCIA = '250102';
    const DM_BAITOA_SANTIAGO = '250104';
    const DM_LA_CANELA = '250105';
    const DM_SAN_FRANCISCO_DE_JACAGUA = '250106';
    const DM_HATO_DEL_YAQUE = '250107';
    const MUN_BISONO = '250200';
    const DM_VILLA_BISONO_NAVARRETE = '250201';
    const MUN_JANICO = '250300';
    const DM_JANICO = '250301';
    const DM_JUNCALITO = '250302';
    const DM_EL_CAIMITO = '250303';
    const MUN_LICEY_AL_MEDIO = '250400';
    const DM_LICEY_AL_MEDIO = '250401';
    const DM_LAS_PALOMAS = '250402';
    const MUN_SAN_JOSE_DE_LAS_MATAS = '250500';
    const DM_SAN_JOSE_DE_LAS_MATAS = '250501';
    const DM_EL_RUBIO = '250502';
    const DM_LA_CUESTA = '250503';
    const DM_LAS_PLACETAS = '250504';
    const MUN_TAMBORIL = '250600';
    const DM_TAMBORIL = '250601';
    const DM_CANCA_LA_PIEDRA = '250602';
    const MUN_VILLA_GONZALEZ = '250700';
    const DM_VILLA_GONZALEZ = '250701';
    const DM_PALMAR_ARRIBA = '250702';
    const DM_EL_LIMON_SANTIAGO = '250703';
    const MUN_PUNAL = '250800';
    const DM_PUNAL = '250801';
    const DM_GUAYABAL_SANTIAGO = '250802';
    const DM_CANABACOA = '250803';
    const MUN_SABANA_IGLESIA = '250900';
    const DM_SABANA_IGLESIA = '250901';
    const MUN_BAITOA = '251000';
    const DM_BAITOA_SANTIAGO_2 = '251001';
    const MUN_SAN_IGNACIO_DE_SABANETA = '260100';
    const DM_SAN_IGNACIO_DE_SABANETA = '260101';
    const MUN_VILLA_LOS_ALMACIGOS = '260200';
    const DM_VILLA_LOS_ALMACIGOS = '260201';
    const MUN_MONCION = '260300';
    const DM_MONCION = '260301';
    const MUN_MAO = '270100';
    const DM_MAO = '270101';
    const DM_AMINA = '270102';
    const DM_JAIBON_PUEBLO_NUEVO = '270103';
    const DM_GUATAPANAL = '270104';
    const MUN_ESPERANZA = '270200';
    const DM_ESPERANZA = '270201';
    const DM_JICOME = '270203';
    const DM_MAIZAL = '270202';
    const DM_BOCA_DE_MAO = '270204';
    const DM_PARADERO = '270205';
    const MUN_LAGUNA_SALADA = '270300';
    const DM_LAGUNA_SALADA = '270301';
    const DM_JAIBON_VALVERDE = '270302';
    const DM_LA_CAYA = '270303';
    const DM_CRUCE_DE_GUAYACANES = '270304';
    const MUN_BONAO = '280100';
    const DM_BONAO = '280101';
    const DM_SABANA_DEL_PUERTO = '280102';
    const DM_JUMA_BEJUCAL = '280103';
    const DM_ARROYO_TORO_MASIPEDRO = '280104';
    const DM_JAYACO = '280105';
    const DM_LA_SALVIA_LOS_QUEMADOS = '280106';
    const MUN_MAIMON = '280200';
    const DM_MAIMON_MONSENOR_NOUEL = '280201';
    const MUN_PIEDRA_BLANCA = '280300';
    const DM_PIEDRA_BLANCA = '280301';
    const DM_VILLA_DE_SONADOR = '280302';
    const DM_JUAN_ADRIAN = '280303';
    const MUN_MONTE_PLATA = '290100';
    const DM_MONTE_PLATA = '290101';
    const DM_DON_JUAN = '290102';
    const DM_CHIRINO = '290103';
    const DM_BOYA = '290104';
    const MUN_BAYAGUANA = '290200';
    const DM_BAYAGUANA = '290201';
    const MUN_SABANA_GRANDE_DE_BOYA = '290300';
    const DM_SABANA_GRANDE_DE_BOYA = '290301';
    const DM_GONZALO = '290302';
    const DM_MAJAGUAL = '290303';
    const MUN_YAMASA = '290400';
    const DM_LOS_BOTADOS = '290402';
    const DM_MAMA_TINGO = '290403';
    const MUN_PERALVILLO = '290500';
    const DM_PERALVILLO = '290501';
    const MUN_HATO_MAYOR = '300100';
    const DM_HATO_MAYOR = '300101';
    const DM_YERBA_BUENA = '300102';
    const DM_MATA_PALACIO = '300103';
    const DM_GUAYABO_DULCE = '300104';
    const MUN_SABANA_DE_LA_MAR = '300200';
    const DM_SABANA_DE_LA_MAR = '300201';
    const DM_ELUPINA_CORDERO_DE_LAS_CANITAS = '300202';
    const MUN_EL_VALLE = '300300';
    const DM_EL_VALLE = '300301';
    const MUN_SAN_JOSE_DE_OCOA = '310100';
    const DM_SAN_JOSE_DE_OCOA = '310101';
    const DM_LA_CIENAGA_SAN_JOSE_DE_OCOA = '310102';
    const DM_NIZAO_LAS_AUYAMAS = '310103';
    const DM_EL_PINAR = '310104';
    const DM_EL_NARANJAL = '310105';
    const MUN_SABANA_LARGA = '310200';
    const DM_SABANA_LARGA = '310201';
    const MUN_RANCHO_ARRIBA = '310300';
    const DM_RANCHO_ARRIBA = '310301';
    const MUN_SANTO_DOMINGO_ESTE = '320100';
    const DM_SANTO_DOMINGO_ESTE = '320101';
    const DM_SAN_LUIS = '320102';
    const MUN_SANTO_DOMINGO_OESTE = '320200';
    const DM_SANTO_DOMINGO_OESTE = '320201';
    const MUN_SANTO_DOMINGO_NORTE = '320300';
    const DM_SANTO_DOMINGO_NORTE = '320301';
    const DM_LA_VICTORIA = '320302';
    const MUN_BOCA_CHICA = '320400';
    const DM_BOCA_CHICA = '320401';
    const DM_LA_CALETA = '320402';
    const MUN_SAN_ANTONIO_DE_GUERRA = '320500';
    const DM_SAN_ANTONIO_DE_GUERRA = '320501';
    const DM_HATO_VIEJO = '320502';
    const MUN_LOS_ALCARRIZOS = '320600';
    const DM_LOS_ALCARRIZOS = '320601';
    const DM_PALMAREJO_VILLA_LINDA = '320602';
    const DM_PANTOJA = '320603';
    const MUN_PEDRO_BRAND = '320700';
    const DM_PEDRO_BRAND = '320701';
    const DM_LA_GUAYIGA = '320702';
    const DM_LA_CUABA = '320703';

    private static $map = [
        Province::DISTRITO_NACIONAL => [
            self::MUN_SANTO_DOMINGO_DE_GUZMAN => 'MUNICIPIO SANTO DOMINGO DE GUZMÁN',
            self::DM_SANTO_DOMINGO_DE_GUZMAN => 'SANTO DOMINGO DE GUZMÁN (D. M.).',
        ],
        Province::AZUA => [
            self::MUN_AZUA => 'MUNICIPIO AZUA',
            self::DM_AZUA => 'AZUA (D. M.).',
            self::DM_BARRO_ARRIBA => 'BARRO ARRIBA (D. M.).',
            self::DM_LAS_BARIAS_LA_ESTANCIA => 'LAS BARÍAS-LA ESTANCIA (D. M.).',
            self::DM_LOS_JOVILLOS => 'LOS JOVILLOS (D. M.).',
            self::DM_PUERTO_VIEJO => 'PUERTO VIEJO (D. M.).',
            self::DM_BARRERAS => 'BARRERAS (D. M.).',
            self::DM_DONA_EMMA_BALAGUER_VIUDA_VALLEJO => 'DOÑA EMMA BALAGUER VIUDA VALLEJO (D. M.).',
            self::DM_CLAVELLINA => 'CLAVELLINA (D. M.).',
            self::DM_LAS_LOMAS => 'LAS LOMAS (D. M.).',
            self::MUN_LAS_CHARCAS => 'MUNICIPIO LAS CHARCAS',
            self::DM_LAS_CHARCAS => 'LAS CHARCAS (D. M.).',
            self::DM_PALMAR_DE_OCOA => 'PALMAR DE OCOA (D. M.).',
            self::MUN_LAS_YAYAS_DE_VIAJAMA => 'MUNICIPIO LAS YAYAS DE VIAJAMA',
            self::DM_LAS_YAYAS_DE_VIAJAMA => 'LAS YAYAS DE VIAJAMA (D. M.).',
            self::DM_VILLARPANDO => 'VILLARPANDO (D. M.).',
            self::DM_HATO_NUEVO_CORTES => 'HATO NUEVO CORTÉS (D. M.).',
            self::MUN_PADRE_LAS_CASAS => 'MUNICIPIO PADRE LAS CASAS',
            self::DM_PADRE_LAS_CASAS => 'PADRE LAS CASAS (D. M.).',
            self::DM_LAS_LAGUNAS_AZUA => 'LAS LAGUNAS (D. M.).',
            self::DM_LA_SIEMBRA => 'LA SIEMBRA (D. M.).',
            self::DM_MONTE_BONITO => 'MONTE BONITO (D. M.).',
            self::DM_LOS_FRIOS => 'LOS FRÍOS (D. M.).',
            self::MUN_PERALTA => 'MUNICIPIO PERALTA',
            self::DM_PERALTA => 'PERALTA (D. M.).',
            self::MUN_SABANA_YEGUA => 'MUNICIPIO SABANA YEGUA',
            self::DM_SABANA_YEGUA => 'SABANA YEGUA (D. M.).',
            self::DM_PROYECTO_4 => 'PROYECTO 4 (D. M.).',
            self::DM_GANADERO => 'GANADERO (D. M.).',
            self::DM_PROYECTO_2_C => 'PROYECTO 2-C (D. M.).',
            self::MUN_PUEBLO_VIEJO => 'MUNICIPIO PUEBLO VIEJO',
            self::DM_PUEBLO_VIEJO => 'PUEBLO VIEJO (D. M.).',
            self::DM_EL_ROSARIO_AZUA => 'EL ROSARIO (D. M.).',
            self::MUN_TABARA_ARRIBA => 'MUNICIPIO TÁBARA ARRIBA',
            self::DM_TABARA_ARRIBA => 'TÁBARA ARRIBA (D. M.).',
            self::DM_TABARA_ABAJO => 'TÁBARA ABAJO (D. M.).',
            self::DM_AMIAMA_GOMEZ => 'AMIAMA GÓMEZ (D. M.).',
            self::DM_LOS_TOROS => 'LOS TOROS (D. M.).',
            self::MUN_GUAYABAL_AZUA => 'MUNICIPIO GUAYABAL',
            self::DM_GUAYABAL_AZUA => 'GUAYABAL (D. M.).',
            self::MUN_ESTEBANIA => 'MUNICIPIO ESTEBANÍA',
            self::DM_ESTEBANIA => 'ESTEBANÍA (D. M.).',
        ],
        Province::BAHORUCO => [
            self::MUN_NEIBA => 'MUNICIPIO NEIBA',
            self::DM_NEIBA => 'NEIBA (D. M.).',
            self::DM_EL_PALMAR => 'EL PALMAR (D. M.).',
            self::MUN_GALVAN => 'MUNICIPIO GALVÁN',
            self::DM_GALVAN => 'GALVÁN (D. M.).',
            self::DM_EL_SALADO => 'EL SALADO (D. M.).',
            self::MUN_TAMAYO => 'MUNICIPIO TAMAYO',
            self::DM_TAMAYO => 'TAMAYO (D. M.).',
            self::DM_UVILLA => 'UVILLA (D. M.).',
            self::DM_SANTANA_BAHORUCO => 'SANTANA (D. M.).',
            self::DM_MONSERRATE => 'MONSERRATE (MONTSERRAT) (D. M.).',
            self::DM_CABEZA_DE_TORO => 'CABEZA DE TORO (D. M.).',
            self::DM_MENA => 'MENA (D. M.).',
            self::DM_SANTA_BARBARA_EL_6 => 'SANTA BÁRBARA EL 6 (D. M.).',
            self::MUN_VILLA_JARAGUA => 'MUNICIPIO VILLA JARAGUA',
            self::DM_VILLA_JARAGUA => 'VILLA JARAGUA (D. M.).',
            self::MUN_LOS_RIOS => 'MUNICIPIO LOS RÍOS',
            self::DM_LOS_RIOS => 'LOS RÍOS (D. M.).',
            self::DM_LAS_CLAVELLINAS_BAHORUCO => 'LAS CLAVELLINAS (D. M.).',
        ],
        Province::BARAHONA => [
            self::MUN_BARAHONA => 'MUNICIPIO BARAHONA',
            self::DM_BARAHONA => 'BARAHONA (D. M.).',
            self::DM_EL_CACHON => 'EL CACHÓN (D. M.).',
            self::DM_LA_GUAZARA => 'LA GUÁZARA (D. M.).',
            self::DM_VILLA_CENTRAL => 'VILLA CENTRAL (D. M.).',
            self::MUN_CABRAL => 'MUNICIPIO CABRAL',
            self::DM_CABRAL => 'CABRAL (D. M.).',
            self::MUN_ENRIQUILLO => 'MUNICIPIO ENRIQUILLO',
            self::DM_ENRIQUILLO => 'ENRIQUILLO (D. M.).',
            self::DM_ARROYO_DULCE => 'ARROYO DULCE (D. M.).',
            self::MUN_PARAISO => 'MUNICIPIO PARAÍSO',
            self::DM_PARAISO => 'PARAÍSO (D. M.).',
            self::DM_LOS_PATOS => 'LOS PATOS (D. M.).',
            self::MUN_VICENTE_NOBLE => 'MUNICIPIO VICENTE NOBLE',
            self::DM_VICENTE_NOBLE => 'VICENTE NOBLE (D. M.).',
            self::DM_CANOA => 'CANOA (D. M.).',
            self::DM_QUITA_CORAZA => 'QUITA CORAZA (D. M.).',
            self::DM_FONDO_NEGRO => 'FONDO NEGRO (D. M.).',
            self::MUN_EL_PENON => 'MUNICIPIO EL PEÑÓN',
            self::DM_EL_PENON => 'EL PEÑÓN (D. M.).',
            self::MUN_LA_CIENAGA_BARAHONA => 'MUNICIPIO LA CIÉNAGA',
            self::DM_LA_CIENAGA_BARAHONA => 'LA CIÉNAGA (D. M.).',
            self::DM_BAHORUCO => 'BAHORUCO (D. M.).',
            self::MUN_FUNDACION => 'MUNICIPIO FUNDACIÓN',
            self::DM_FUNDACION => 'FUNDACIÓN (D. M.).',
            self::DM_PESCADERIA => 'PESCADERÍA (D. M.).',
            self::MUN_LAS_SALINAS => 'MUNICIPIO LAS SALINAS',
            self::DM_LAS_SALINAS => 'LAS SALINAS (D. M.).',
            self::MUN_POLO => 'MUNICIPIO POLO',
            self::DM_POLO => 'POLO (D. M.).',
            self::MUN_JAQUIMEYES => 'MUNICIPIO JAQUIMEYES',
            self::DM_JAQUIMEYES => 'JAQUIMEYES (D. M.).',
            self::DM_PALO_ALTO => 'PALO ALTO (D. M.).',
        ],
        Province::DAJABON => [
            self::MUN_DAJABON => 'MUNICIPIO DAJABÓN',
            self::DM_DAJABON => 'DAJABÓN (D. M.).',
            self::DM_CANONGO => 'CAÑONGO (D. M.).',
            self::MUN_LOMA_DE_CABRERA => 'MUNICIPIO LOMA DE CABRERA',
            self::DM_LOMA_DE_CABRERA => 'LOMA DE CABRERA (D. M.).',
            self::DM_CAPOTILLO => 'CAPOTILLO (D. M.).',
            self::DM_SANTIAGO_DE_LA_CRUZ => 'SANTIAGO DE LA CRUZ (D. M.).',
            self::MUN_PARTIDO => 'MUNICIPIO PARTIDO',
            self::DM_PARTIDO => 'PARTIDO (D. M.).',
            self::MUN_RESTAURACION => 'MUNICIPIO RESTAURACIÓN',
            self::DM_RESTAURACION => 'RESTAURACIÓN (D. M.).',
            self::MUN_EL_PINO => 'MUNICIPIO EL PINO',
            self::DM_EL_PINO => 'EL PINO (D. M.).',
            self::DM_MANUEL_BUENO => 'MANUEL BUENO (D. M.).',
        ],
        Province::DUARTE => [
            self::MUN_SAN_FRANCISCO_DE_MACORIS => 'MUNICIPIO SAN FRANCISCO DE MACORÍS',
            self::DM_SAN_FRANCISCO_DE_MACORIS => 'SAN FRANCISCO DE MACORÍS (D. M.).',
            self::DM_LA_PENA => 'LA PEÑA (D. M.).',
            self::DM_CENOVI => 'CENOVÍ (D. M.).',
            self::DM_JAYA => 'JAYA (D. M.).',
            self::DM_PRESIDENTE_DON_ANTONIO_GUZMAN_FERNANDEZ => 'PRESIDENTE DON ANTONIO GUZMÁN FERNÁNDEZ (D. M.).',
            self::MUN_ARENOSO => 'MUNICIPIO ARENOSO',
            self::DM_ARENOSO => 'ARENOSO (D. M.).',
            self::DM_LAS_COLES => 'LAS COLES (D. M.).',
            self::DM_EL_AGUACATE => 'EL AGUACATE (D. M.).',
            self::MUN_CASTILLO => 'MUNICIPIO CASTILLO',
            self::DM_CASTILLO => 'CASTILLO (D. M.).',
            self::MUN_PIMENTEL => 'MUNICIPIO PIMENTEL',
            self::DM_PIMENTEL => 'PIMENTEL (D. M.).',
            self::MUN_VILLA_RIVA => 'MUNICIPIO VILLA RIVA',
            self::DM_VILLA_RIVA => 'VILLA RIVA (D. M.).',
            self::DM_AGUA_SANTA_DEL_YUNA => 'AGUA SANTA DEL YUNA (D. M.).',
            self::DM_CRISTO_REY_DE_GUARAGUAO => 'CRISTO REY DE GUARAGUAO (D. M.).',
            self::DM_LAS_TARANAS => 'LAS TARANAS (D. M.).',
            self::DM_BARRAQUITO => 'BARRAQUITO (D. M.).',
            self::MUN_LAS_GUARANAS => 'MUNICIPIO LAS GUÁRANAS',
            self::DM_LAS_GUARANAS => 'LAS GUÁRANAS (D. M.).',
            self::MUN_EUGENIO_MARIA_DE_HOSTOS => 'MUNICIPIO EUGENIO MARÍA DE HOSTOS',
            self::DM_EUGENIO_MARIA_DE_HOSTOS => 'EUGENIO MARÍA DE HOSTOS (D. M.).',
            self::DM_SABANA_GRANDE_DUARTE => 'SABANA GRANDE (D. M.).',
        ],
        Province::ELIAS_PINA => [
            self::MUN_COMENDADOR => 'MUNICIPIO COMENDADOR',
            self::DM_COMENDADOR => 'COMENDADOR (D. M.).',
            self::DM_SABANA_LARGA_ELIAS_PINA => 'SABANA LARGA (D. M.).',
            self::DM_GUAYABO => 'GUAYABO (D. M.).',
            self::MUN_BANICA => 'MUNICIPIO BÁNICA',
            self::DM_BANICA => 'BÁNICA (D. M.).',
            self::DM_SABANA_CRUZ => 'SABANA CRUZ (D. M.).',
            self::DM_SABANA_HIGUERO => 'SABANA HIGÜERO (D. M.).',
            self::MUN_EL_LLANO => 'MUNICIPIO EL LLANO',
            self::DM_EL_LLANO => 'EL LLANO (D. M.).',
            self::DM_GUANITO_ELIAS_PINA => 'GUANITO (D. M.).',
            self::MUN_HONDO_VALLE => 'MUNICIPIO HONDO VALLE',
            self::DM_HONDO_VALLE => 'HONDO VALLE (D. M.).',
            self::DM_RANCHO_DE_LA_GUARDIA => 'RANCHO DE LA GUARDIA (D. M.).',
            self::MUN_PEDRO_SANTANA => 'MUNICIPIO PEDRO SANTANA',
            self::DM_PEDRO_SANTANA => 'PEDRO SANTANA (D. M.).',
            self::DM_RIO_LIMPIO => 'RÍO LIMPIO (D. M.).',
            self::MUN_JUAN_SANTIAGO => 'MUNICIPIO JUAN SANTIAGO',
            self::DM_JUAN_SANTIAGO => 'JUAN SANTIAGO (D. M.).',
        ],
        Province::EL_SEIBO => [
            self::MUN_EL_SEIBO => 'MUNICIPIO EL SEIBO',
            self::DM_EL_SEIBO => 'EL SEIBO (D. M.).',
            self::DM_PEDRO_SANCHEZ => 'PEDRO SÁNCHEZ (D. M.).',
            self::DM_SAN_FRANCISCO_VICENTILLO => 'SAN FRANCISCO-VICENTILLO (D. M.).',
            self::DM_SANTA_LUCIA => 'SANTA LUCÍA (D. M.).',
            self::MUN_MICHES => 'MUNICIPIO MICHES',
            self::DM_MICHES => 'MICHES (D. M.).',
            self::DM_EL_CEDRO => 'EL CEDRO (D. M.).',
            self::DM_LA_GINA => 'LA GINA (D. M.).',
        ],
        Province::ESPAILLAT => [
            self::MUN_MOCA => 'MUNICIPIO MOCA',
            self::DM_MOCA => 'MOCA (D. M.).',
            self::DM_JOSE_CONTRERAS => 'JOSÉ CONTRERAS (D. M.).',
            self::DM_SAN_VICTOR => 'SAN VÍCTOR (D. M.).',
            self::DM_JUAN_LOPEZ => 'JUAN LÓPEZ (D. M.).',
            self::DM_LAS_LAGUNAS_ESPAILLAT => 'LAS LAGUNAS (D. M.).',
            self::DM_CANCA_LA_REYNA => 'CANCA LA REYNA (D. M.).',
            self::DM_EL_HIGUERITO => 'EL HIGÜERITO (D. M.).',
            self::DM_MONTE_DE_LA_JAGUA => 'MONTE DE LA JAGUA (D. M.).',
            self::DM_LA_ORTEGA => 'LA ORTEGA (D. M.).',
            self::MUN_CAYETANO_GERMOSEN => 'MUNICIPIO CAYETANO GERMOSÉN',
            self::DM_CAYETANO_GERMOSEN => 'CAYETANO GERMOSÉN (D. M.).',
            self::MUN_GASPAR_HERNANDEZ => 'MUNICIPIO GASPAR HERNÁNDEZ',
            self::DM_GASPAR_HERNANDEZ => 'GASPAR HERNÁNDEZ (D. M.).',
            self::DM_JOBA_ARRIBA => 'JOBA ARRIBA (D. M.).',
            self::DM_VERAGUA => 'VERAGUA (D. M.).',
            self::DM_VILLA_MAGANTE => 'VILLA MAGANTE (D. M.).',
            self::MUN_JAMAO_AL_NORTE => 'MUNICIPIO JAMAO AL NORTE',
            self::DM_JAMAO_AL_NORTE => 'JAMAO AL NORTE (D. M.).',
        ],
        Province::INDEPENDENCIA => [
            self::MUN_JIMANI => 'MUNICIPIO JIMANÍ',
            self::DM_JIMANI => 'JIMANÍ (D. M.).',
            self::DM_EL_LIMON_INDEPENDENCIA => 'EL LIMÓN (D. M.).',
            self::DM_BOCA_DE_CACHON => 'BOCA DE CACHÓN (D. M.).',
            self::MUN_DUVERGE => 'MUNICIPIO DUVERGÉ',
            self::DM_DUVERGE => 'DUVERGÉ (D. M.).',
            self::DM_VENGAN_A_VER => 'VENGAN A VER (D. M.).',
            self::MUN_LA_DESCUBIERTA => 'MUNICIPIO LA DESCUBIERTA',
            self::DM_LA_DESCUBIERTA => 'LA DESCUBIERTA (D. M.).',
            self::MUN_POSTRER_RIO => 'MUNICIPIO POSTRER RÍO',
            self::DM_POSTRER_RIO => 'POSTRER RÍO (D. M.).',
            self::DM_GUAYABAL_INDEPENDENCIA => 'GUAYABAL (D. M.).',
            self::MUN_CRISTOBAL => 'MUNICIPIO CRISTÓBAL',
            self::DM_CRISTOBAL => 'CRISTÓBAL (D. M.).',
            self::DM_BATEY_8 => 'BATEY 8 (D. M.).',
            self::MUN_MELLA => 'MUNICIPIO MELLA',
            self::DM_MELLA => 'MELLA (D. M.).',
            self::DM_LA_COLONIA => 'LA COLONIA (D. M.).',
        ],
        Province::LA_ALTAGRACIA => [
            self::MUN_HIGUEY => 'MUNICIPIO HIGÜEY',
            self::DM_HIGUEY => 'HIGÜEY (D. M.).',
            self::DM_LAS_LAGUNAS_DE_NISIBON => 'LAS LAGUNAS DE NISIBÓN (D. M.).',
            self::DM_LA_OTRA_BANDA => 'LA OTRA BANDA (D. M.).',
            self::DM_VERON_PUNTA_CANA => 'VERÓN PUNTA CANA (D. M.) (Incluye Bávaro)',
            self::MUN_SAN_RAFAEL_DEL_YUMA => 'MUNICIPIO SAN RAFAEL DEL YUMA',
            self::DM_SAN_RAFAEL_DEL_YUMA => 'SAN RAFAEL DEL YUMA (D. M.).',
            self::DM_BOCA_DE_YUMA => 'BOCA DE YUMA (D. M.).',
            self::DM_BAYAHIBE => 'BAYAHÍBE (D. M.).',
        ],
        Province::LA_ROMANA => [
            self::MUN_LA_ROMANA => 'MUNICIPIO LA ROMANA',
            self::DM_LA_ROMANA => 'LA ROMANA (D. M.).',
            self::DM_CALETA => 'CALETA (D. M.).',
            self::MUN_GUAYMATE => 'MUNICIPIO GUAYMATE',
            self::DM_GUAYMATE => 'GUAYMATE (D. M.).',
            self::MUN_VILLA_HERMOSA => 'MUNICIPIO VILLA HERMOSA',
            self::DM_VILLA_HERMOSA => 'VILLA HERMOSA (D. M.).',
            self::DM_CUMAYASA => 'CUMAYASA (D. M.).',
        ],
        Province::LA_VEGA => [
            self::MUN_LA_VEGA => 'MUNICIPIO LA VEGA',
            self::DM_LA_VEGA => 'LA VEGA (D. M.).',
            self::DM_RIO_VERDE_ARRIBA => 'RÍO VERDE ARRIBA (D. M.).',
            self::DM_EL_RANCHITO => 'EL RANCHITO (D. M.).',
            self::DM_TAVERAS => 'TAVERAS (D. M.).',
            self::DM_DON_JUAN_RODRIGUEZ => 'DON JUAN RODRÍGUEZ (D.M.)',
            self::MUN_CONSTANZA => 'MUNICIPIO CONSTANZA',
            self::DM_CONSTANZA => 'CONSTANZA (D. M.).',
            self::DM_TIREO => 'TIREO (D. M.).',
            self::DM_LA_SABINA => 'LA SABINA (D. M.).',
            self::MUN_JARABACOA => 'MUNICIPIO JARABACOA',
            self::DM_JARABACOA => 'JARABACOA (D. M.).',
            self::DM_BUENA_VISTA => 'BUENA VISTA (D. M.).',
            self::DM_MANABAO => 'MANABAO (D. M.).',
            self::MUN_JIMA_ABAJO => 'MUNICIPIO JIMA ABAJO',
            self::DM_JIMA_ABAJO => 'JIMA ABAJO (D. M.).',
            self::DM_RINCON => 'RINCÓN (D. M.).',
        ],
        Province::MARIA_TRINIDAD_SANCHEZ => [
            self::MUN_NAGUA => 'MUNICIPIO NAGUA',
            self::DM_NAGUA => 'NAGUA (D. M.).',
            self::DM_SAN_JOSE_DE_MATANZAS => 'SAN JOSÉ DE MATANZAS (D. M.).',
            self::DM_LAS_GORDAS => 'LAS GORDAS (D. M.).',
            self::DM_ARROYO_AL_MEDIO => 'ARROYO AL MEDIO (D. M.).',
            self::MUN_CABRERA => 'MUNICIPIO CABRERA',
            self::DM_CABRERA => 'CABRERA (D. M.).',
            self::DM_ARROYO_SALADO => 'ARROYO SALADO (D. M.).',
            self::DM_LA_ENTRADA => 'LA ENTRADA (D. M.).',
            self::MUN_EL_FACTOR => 'MUNICIPIO EL FACTOR',
            self::DM_EL_FACTOR => 'EL FACTOR (D. M.).',
            self::DM_EL_POZO => 'EL POZO (D. M.).',
            self::MUN_RIO_SAN_JUAN => 'MUNICIPIO RÍO SAN JUAN',
            self::DM_RIO_SAN_JUAN => 'RÍO SAN JUAN (D. M.).',
        ],
        Province::MONTE_CRISTI => [
            self::MUN_MONTE_CRISTI => 'MUNICIPIO MONTE CRISTI',
            self::DM_MONTE_CRISTI => 'MONTE CRISTI (D. M.).',
            self::MUN_CASTANUELAS => 'MUNICIPIO CASTAÑUELAS',
            self::DM_CASTANUELAS => 'CASTAÑUELAS (D. M.).',
            self::DM_PALO_VERDE => 'PALO VERDE (D. M.).',
            self::MUN_GUAYUBIN => 'MUNICIPIO GUAYUBÍN',
            self::DM_GUAYUBIN => 'GUAYUBÍN (D. M.).',
            self::DM_VILLA_ELISA => 'VILLA ELISA (D. M.).',
            self::DM_HATILLO_PALMA => 'HATILLO PALMA (D. M.).',
            self::DM_CANA_CHAPETON => 'CANA CHAPETÓN (D. M.).',
            self::MUN_LAS_MATAS_DE_SANTA_CRUZ => 'MUNICIPIO LAS MATAS DE SANTA CRUZ',
            self::DM_LAS_MATAS_DE_SANTA_CRUZ => 'LAS MATAS DE SANTA CRUZ (D. M.).',
            self::MUN_PEPILLO_SALCEDO => 'MUNICIPIO PEPILLO SALCEDO',
            self::DM_PEPILLO_SALCEDO_MANZANILLO => 'PEPILLO SALCEDO (MANZANILLO)',
            self::DM_SANTA_MARIA => 'SANTA MARÍA (D. M.)',
            self::MUN_VILLA_VASQUEZ => 'MUNICIPIO VILLA VÁSQUEZ',
            self::DM_VILLA_VASQUEZ => 'VILLA VÁSQUEZ',
        ],
        Province::PEDERNALES => [
            self::MUN_PEDERNALES => 'MUNICIPIO PEDERNALES',
            self::DM_PEDERNALES => 'PEDERNALES',
            self::DM_JOSE_FRANCISCO_PENA_GOMEZ => 'JOSÉ FRANCISCO PEÑA GÓMEZ (D. M.).',
            self::MUN_OVIEDO => 'MUNICIPIO OVIEDO',
            self::DM_OVIEDO => 'OVIEDO',
            self::DM_JUANCHO => 'JUANCHO (D. M.).',
        ],
        Province::PERAVIA => [
            self::MUN_BANI => 'MUNICIPIO BANÍ',
            self::DM_BANI => 'BANÍ (D. M.).',
            self::DM_MATANZAS_PERAVIA_1 => 'MATANZAS (D. M.).',
            self::DM_VILLA_FUNDACION => 'VILLA FUNDACIÓN (D. M.).',
            self::DM_SABANA_BUEY => 'SABANA BUEY (D. M.).',
            self::DM_PAYA => 'PAYA (D. M.).',
            self::DM_VILLA_SOMBRERO => 'VILLA SOMBRERO (D. M.).',
            self::DM_EL_CARRETON => 'EL CARRETÓN (D. M.).',
            self::DM_CATALINA => 'CATALINA (D. M.).',
            self::DM_EL_LIMONAL_PERAVIA => 'EL LIMONAL (D. M.).',
            self::DM_LAS_BARIAS_PERAVIA => 'LAS BARÍAS (D. M.).',
            self::MUN_NIZAO => 'MUNICIPIO NIZAO',
            self::DM_NIZAO => 'NIZAO',
            self::DM_PIZARRETE => 'PIZARRETE (D. M.).',
            self::DM_SANTANA_PERAVIA => 'SANTANA (D. M.).',
            self::MUN_MATANZAS => 'MATANZAS',
            self::DM_MATANZAS_PERAVIA_2 => 'MATANZAS',
        ],
        Province::PUERTO_PLATA => [
            self::MUN_PUERTO_PLATA => 'MUNICIPIO PUERTO PLATA',
            self::DM_PUERTO_PLATA => 'PUERTO PLATA (D. M.).',
            self::DM_YASICA_ARRIBA => 'YÁSICA ARRIBA (D. M.).',
            self::DM_MAIMON_PUERTO_PLATA => 'MAIMÓN (D. M.).',
            self::MUN_ALTAMIRA => 'MUNICIPIO ALTAMIRA',
            self::DM_ALTAMIRA => 'ALTAMIRA',
            self::DM_RIO_GRANDE => 'RÍO GRANDE (D. M.).',
            self::MUN_GUANANICO => 'MUNICIPIO GUANANICO',
            self::DM_GUANANICO => 'GUANANICO',
            self::MUN_IMBERT => 'MUNICIPIO IMBERT',
            self::DM_IMBERT => 'IMBERT',
            self::MUN_LOS_HIDALGOS => 'MUNICIPIO LOS HIDALGOS',
            self::DM_LOS_HIDALGOS => 'LOS HIDALGOS',
            self::DM_NAVAS => 'NAVAS (D. M.).',
            self::MUN_LUPERON => 'MUNICIPIO LUPERÓN',
            self::DM_LUPERON => 'LUPERÓN',
            self::DM_LA_ISABELA => 'LA ISABELA (D. M.).',
            self::DM_BELLOSO => 'BELLOSO (D. M.).',
            self::DM_EL_ESTRECHO_DE_LUPERON_OMAR_BROSS => 'EL ESTRECHO DE LUPERÓN OMAR BROSS (D. M.).',
            self::MUN_SOSUA => 'MUNICIPIO SOSÚA',
            self::DM_SOSUA => 'SOSÚA',
            self::DM_CABARETE => 'CABARETE (D. M.).',
            self::DM_SABANETA_DE_YASICA => 'SABANETA DE YÁSICA (D. M.).',
            self::MUN_VILLA_ISABELA => 'MUNICIPIO VILLA ISABELA',
            self::DM_VILLA_ISABELA => 'VILLA ISABELA',
            self::DM_ESTERO_HONDO => 'ESTERO HONDO (D. M.).',
            self::DM_LA_JAIBA => 'LA JAIBA (D. M.).',
            self::DM_GUALETE => 'GUALETE (D. M.).',
            self::MUN_VILLA_MONTELLANO => 'MUNICIPIO VILLA MONTELLANO',
            self::DM_VILLA_MONTELLANO => 'VILLA MONTELLANO',
        ],
        Province::HERMANAS_MIRABAL => [
            self::MUN_SALCEDO => 'MUNICIPIO SALCEDO',
            self::DM_SALCEDO => 'SALCEDO',
            self::DM_JAMAO_AFUERA => 'JAMAO AFUERA (D. M.).',
            self::MUN_TENARES => 'MUNICIPIO TENARES',
            self::DM_TENARES => 'TENARES',
            self::DM_BLANCO => 'BLANCO (D. M.).',
            self::MUN_VILLA_TAPIA => 'MUNICIPIO VILLA TAPIA',
            self::DM_VILLA_TAPIA => 'VILLA TAPIA',
        ],
        Province::SAMANA => [
            self::MUN_SAMANA => 'MUNICIPIO SAMANÁ',
            self::DM_SAMANA => 'SAMANÁ',
            self::DM_EL_LIMON_SAMANA => 'EL LIMÓN (D. M.).',
            self::DM_ARROYO_BARRIL => 'ARROYO BARRIL (D. M.).',
            self::DM_LAS_GALERAS => 'LAS GALERAS (D. M.).',
            self::MUN_SANCHEZ => 'MUNICIPIO SÁNCHEZ',
            self::DM_SANCHEZ => 'SÁNCHEZ (D. M.).',
            self::MUN_LAS_TERRENAS => 'MUNICIPIO LAS TERRENAS',
            self::DM_LAS_TERRENAS => 'LAS TERRENAS',
        ],
        Province::SAN_CRISTOBAL => [
            self::MUN_SAN_CRISTOBAL => 'MUNICIPIO SAN CRISTÓBAL',
            self::DM_SAN_CRISTOBAL => 'SAN CRISTÓBAL (D. M.).',
            self::DM_HATO_DAMAS => 'HATO DAMAS (D. M.).',
            self::DM_HATILLO => 'HATILLO (D. M.).',
            self::MUN_SABANA_GRANDE_DE_PALENQUE => 'MUNICIPIO SABANA GRANDE DE PALENQUE',
            self::DM_SABANA_GRANDE_DE_PALENQUE => 'SABANA GRANDE DE PALENQUE (D. M.).',
            self::MUN_BAJOS_DE_HAINA => 'MUNICIPIO BAJOS DE HAINA',
            self::DM_BAJOS_DE_HAINA => 'BAJOS DE HAINA',
            self::DM_EL_CARRIL => 'EL CARRIL (D. M.).',
            self::DM_QUITA_SUENO_SAN_CRISTOBAL => 'QUITA SUEÑO (D. M.).',
            self::MUN_CAMBITA_GARABITOS => 'MUNICIPIO CAMBITA GARABITOS',
            self::DM_CAMBITA_GARABITOS => 'CAMBITA GARABITOS',
            self::DM_CAMBITA_EL_PUEBLECITO => 'CAMBITA EL PUEBLECITO (D. M.).',
            self::MUN_VILLA_ALTAGRACIA => 'MUNICIPIO VILLA ALTAGRACIA',
            self::DM_VILLA_ALTAGRACIA => 'VILLA ALTAGRACIA',
            self::DM_SAN_JOSE_DEL_PUERTO => 'SAN JOSÉ DEL PUERTO (D. M.).',
            self::DM_MEDINA => 'MEDINA (D. M.).',
            self::DM_LA_CUCHILLA => 'LA CUCHILLA (D. M.).',
            self::MUN_YAGUATE => 'MUNICIPIO YAGUATE',
            self::DM_YAGUATE => 'YAGUATE (D. M.).',
            self::DM_DONA_ANA => 'DOÑA ANA (D. M.)',
            self::MUN_SAN_GREGORIO_DE_NIGUA => 'MUNICIPIO SAN GREGORIO DE NIGUA',
            self::DM_SAN_GREGORIO_DE_NIGUA => 'SAN GREGORIO DE NIGUA',
            self::MUN_LOS_CACAOS => 'MUNICIPIO LOS CACAOS',
            self::DM_LOS_CACAOS => 'LOS CACAOS (D. M.).',
        ],
        Province::SAN_JUAN => [
            self::MUN_SAN_JUAN => 'MUNICIPIO SAN JUAN',
            self::DM_SAN_JUAN => 'SAN JUAN',
            self::DM_PEDRO_CORTO => 'PEDRO CORTO (D. M.).',
            self::DM_SABANETA => 'SABANETA (D. M.).',
            self::DM_SABANA_ALTA => 'SABANA ALTA (D. M.).',
            self::DM_EL_ROSARIO_SAN_JUAN => 'EL ROSARIO (D. M.).',
            self::DM_HATO_DEL_PADRE => 'HATO DEL PADRE (D. M.).',
            self::DM_GUANITO_SAN_JUAN => 'GUANITO (D. M.).',
            self::DM_LA_JAGUA => 'LA JAGUA (D. M.).',
            self::DM_LAS_MAGUANAS_HATO_NUEVO => 'LAS MAGUANAS-HATO NUEVO (D. M.).',
            self::DM_LAS_CHARCAS_DE_MARIA_NOVA => 'LAS CHARCAS DE MARÍA NOVA (D. M.).',
            self::DM_LAS_ZANJAS => 'LAS ZANJAS (D. M.)',
            self::MUN_BOHECHIO => 'MUNICIPIO BOHECHÍO',
            self::DM_BOHECHIO => 'BOHECHÍO',
            self::DM_ARROYO_CANO => 'ARROYO CANO (D. M.).',
            self::DM_YAQUE => 'YAQUE (D. M.).',
            self::MUN_EL_CERCADO => 'MUNICIPIO EL CERCADO',
            self::DM_EL_CERCADO => 'EL CERCADO',
            self::DM_DERRUMBADERO => 'DERRUMBADERO (D. M.)',
            self::DM_BATISTA => 'BATISTA (D. M.)',
            self::MUN_JUAN_DE_HERRERA => 'MUNICIPIO JUAN DE HERRERA',
            self::DM_JUAN_DE_HERRERA => 'JUAN DE HERRERA',
            self::DM_JINOVA => 'JÍNOVA (D. M.).',
            self::MUN_LAS_MATAS_DE_FARFAN => 'MUNICIPIO LAS MATAS DE FARFÁN',
            self::DM_LAS_MATAS_DE_FARFAN => 'LAS MATAS DE FARFÁN',
            self::DM_MATAYAYA => 'MATAYAYA (D. M.).',
            self::DM_CARRERA_DE_YEGUAS => 'CARRERA DE YEGUAS (D. M.).',
            self::MUN_VALLEJUELO => 'MUNICIPIO VALLEJUELO',
            self::DM_VALLEJUELO => 'VALLEJUELO',
            self::DM_JORJILLO => 'JORJILLO (D. M.).',
        ],
        Province::SAN_PEDRO_DE_MACORIS => [
            self::MUN_SAN_PEDRO_DE_MACORIS => 'MUNICIPIO SAN PEDRO DE MACORÍS',
            self::DM_SAN_PEDRO_DE_MACORIS => 'SAN PEDRO DE MACORÍS',
            self::MUN_LOS_LLANOS => 'MUNICIPIO LOS LLANOS',
            self::DM_LOS_LLANOS => 'LOS LLANOS',
            self::DM_EL_PUERTO => 'EL PUERTO (D. M.).',
            self::DM_GAUTIER => 'GAUTIER (D. M.).',
            self::MUN_RAMON_SANTANA => 'MUNICIPIO RAMÓN SANTANA',
            self::DM_RAMON_SANTANA => 'RAMÓN SANTANA',
            self::MUN_CONSUELO => 'MUNICIPIO CONSUELO',
            self::DM_CONSUELO => 'CONSUELO',
            self::MUN_QUISQUEYA => 'MUNICIPIO QUISQUEYA',
            self::DM_QUISQUEYA => 'QUISQUEYA',
            self::MUN_GUAYACANES => 'MUNICIPIO GUAYACANES',
            self::DM_GUAYACANES => 'GUAYACANES',
        ],
        Province::SANCHEZ_RAMIREZ => [
            self::MUN_COTUI => 'MUNICIPIO COTUÍ',
            self::DM_COTUI => 'COTUÍ',
            self::DM_QUITA_SUENO_SANCHEZ_RAMIREZ => 'QUITA SUEÑO (D. M.).',
            self::DM_CABALLERO => 'CABALLERO (D. M.).',
            self::DM_COMEDERO_ARRIBA => 'COMEDERO ARRIBA (D. M.).',
            self::DM_PLATANAL => 'PLATANAL (D. M.).',
            self::DM_ZAMBRANA_ABAJO => 'ZAMBRANA ABAJO',
            self::MUN_CEVICOS => 'MUNICIPIO CEVICOS',
            self::DM_CEVICOS => 'CEVICOS',
            self::DM_LA_CUEVA => 'LA CUEVA (D. M.).',
            self::MUN_FANTINO => 'MUNICIPIO FANTINO',
            self::DM_FANTINO => 'FANTINO',
            self::MUN_LA_MATA => 'MUNICIPIO LA MATA',
            self::DM_LA_MATA => 'LA MATA',
            self::DM_LA_BIJA => 'LA BIJA (D. M.).',
            self::DM_ANGELINA => 'ANGELINA (D. M.).',
            self::DM_HERNANDO_ALONZO => 'HERNANDO ALONZO (D. M.).',
        ],
        Province::SANTIAGO => [
            self::MUN_SANTIAGO => 'MUNICIPIO SANTIAGO',
            self::DM_SANTIAGO => 'SANTIAGO',
            self::DM_PEDRO_GARCIA => 'PEDRO GARCÍA (D. M.).',
            self::DM_BAITOA_SANTIAGO => 'BAITOA (D. M.).',
            self::DM_LA_CANELA => 'LA CANELA (D. M.).',
            self::DM_SAN_FRANCISCO_DE_JACAGUA => 'SAN FRANCISCO DE JACAGUA (D. M.).',
            self::DM_HATO_DEL_YAQUE => 'HATO DEL YAQUE (D. M.).',
            self::MUN_BISONO => 'MUNICIPIO BISONÓ',
            self::DM_VILLA_BISONO_NAVARRETE => 'VILLA BISONÓ (NAVARRETE) (D. M.).',
            self::MUN_JANICO => 'MUNICIPIO JÁNICO',
            self::DM_JANICO => 'JÁNICO',
            self::DM_JUNCALITO => 'JUNCALITO (D. M.).',
            self::DM_EL_CAIMITO => 'EL CAIMITO (D. M.).',
            self::MUN_LICEY_AL_MEDIO => 'MUNICIPIO LICEY AL MEDIO',
            self::DM_LICEY_AL_MEDIO => 'LICEY AL MEDIO',
            self::DM_LAS_PALOMAS => 'LAS PALOMAS (D. M.).',
            self::MUN_SAN_JOSE_DE_LAS_MATAS => 'MUNICIPIO SAN JOSÉ DE LAS MATAS',
            self::DM_SAN_JOSE_DE_LAS_MATAS => 'SAN JOSÉ DE LAS MATAS',
            self::DM_EL_RUBIO => 'EL RUBIO (D. M.).',
            self::DM_LA_CUESTA => 'LA CUESTA (D. M.).',
            self::DM_LAS_PLACETAS => 'LAS PLACETAS (D. M.).',
            self::MUN_TAMBORIL => 'MUNICIPIO TAMBORIL',
            self::DM_TAMBORIL => 'TAMBORIL',
            self::DM_CANCA_LA_PIEDRA => 'CANCA LA PIEDRA (D. M.).',
            self::MUN_VILLA_GONZALEZ => 'MUNICIPIO VILLA GONZÁLEZ',
            self::DM_VILLA_GONZALEZ => 'VILLA GONZÁLEZ',
            self::DM_PALMAR_ARRIBA => 'PALMAR ARRIBA (D. M.).',
            self::DM_EL_LIMON_SANTIAGO => 'EL LIMÓN (D. M.).',
            self::MUN_PUNAL => 'MUNICIPIO PUÑAL',
            self::DM_PUNAL => 'PUÑAL',
            self::DM_GUAYABAL_SANTIAGO => 'GUAYABAL (D. M.).',
            self::DM_CANABACOA => 'CANABACOA (D. M.).',
            self::MUN_SABANA_IGLESIA => 'MUNICIPIO SABANA IGLESIA',
            self::DM_SABANA_IGLESIA => 'SABANA IGLESIA',
            self::MUN_BAITOA => 'BAITOA',
            self::DM_BAITOA_SANTIAGO_2 => 'BAITOA',
        ],
        Province::SANTIAGO_RODRIGUEZ => [
            self::MUN_SAN_IGNACIO_DE_SABANETA => 'MUNICIPIO SAN IGNACIO DE SABANETA',
            self::DM_SAN_IGNACIO_DE_SABANETA => 'SAN IGNACIO DE SABANETA (D. M.).',
            self::MUN_VILLA_LOS_ALMACIGOS => 'MUNICIPIO VILLA LOS ALMÁCIGOS',
            self::DM_VILLA_LOS_ALMACIGOS => 'VILLA LOS ALMÁCIGOS (D. M.).',
            self::MUN_MONCION => 'MUNICIPIO MONCIÓN',
            self::DM_MONCION => 'MONCIÓN (D. M.).',
        ],
        Province::VALVERDE => [
            self::MUN_MAO => 'MUNICIPIO MAO',
            self::DM_MAO => 'MAO (D. M.).',
            self::DM_AMINA => 'AMINA (D. M.).',
            self::DM_JAIBON_PUEBLO_NUEVO => 'JAIBÓN (PUEBLO NUEVO) (D. M.).',
            self::DM_GUATAPANAL => 'GUATAPANAL (D. M.).',
            self::MUN_ESPERANZA => 'MUNICIPIO ESPERANZA',
            self::DM_ESPERANZA => 'ESPERANZA',
            self::DM_MAIZAL => 'MAIZAL (D. M.).',
            self::DM_JICOME => 'JICOMÉ (D. M.).',
            self::DM_BOCA_DE_MAO => 'BOCA DE MAO (D. M.).',
            self::DM_PARADERO => 'PARADERO (D. M.).',
            self::MUN_LAGUNA_SALADA => 'MUNICIPIO LAGUNA SALADA',
            self::DM_LAGUNA_SALADA => 'LAGUNA SALADA (D. M.).',
            self::DM_JAIBON_VALVERDE => 'JAIBÓN (D. M.).',
            self::DM_LA_CAYA => 'LA CAYA (D. M.).',
            self::DM_CRUCE_DE_GUAYACANES => 'CRUCE DE GUAYACANES (D. M.).',
        ],
        Province::MONSENOR_NOUEL => [
            self::MUN_BONAO => 'MUNICIPIO BONAO',
            self::DM_BONAO => 'BONAO (D. M.).',
            self::DM_SABANA_DEL_PUERTO => 'SABANA DEL PUERTO (D. M.).',
            self::DM_JUMA_BEJUCAL => 'JUMA BEJUCAL (D. M.).',
            self::DM_ARROYO_TORO_MASIPEDRO => 'ARROYO TORO - MASIPEDRO (D. M.).',
            self::DM_JAYACO => 'JAYACO (D. M.).',
            self::DM_LA_SALVIA_LOS_QUEMADOS => 'LA SALVIA - LOS QUEMADOS (D. M.).',
            self::MUN_MAIMON => 'MUNICIPIO MAIMÓN',
            self::DM_MAIMON_MONSENOR_NOUEL => 'MAIMÓN (D. M.).',
            self::MUN_PIEDRA_BLANCA => 'MUNICIPIO PIEDRA BLANCA',
            self::DM_PIEDRA_BLANCA => 'PIEDRA BLANCA (D. M.).',
            self::DM_VILLA_DE_SONADOR => 'VILLA DE SONADOR (D. M.).',
            self::DM_JUAN_ADRIAN => 'JUAN ADRIÁN (D. M.).',
        ],
        Province::MONTE_PLATA => [
            self::MUN_MONTE_PLATA => 'MUNICIPIO MONTE PLATA',
            self::DM_MONTE_PLATA => 'MONTE PLATA (D. M.).',
            self::DM_DON_JUAN => 'DON JUAN (D. M.).',
            self::DM_CHIRINO => 'CHIRINO (D. M.).',
            self::DM_BOYA => 'BOYÁ (D. M.).',
            self::MUN_BAYAGUANA => 'MUNICIPIO BAYAGUANA',
            self::DM_BAYAGUANA => 'BAYAGUANA (D. M.).',
            self::MUN_SABANA_GRANDE_DE_BOYA => 'MUNICIPIO SABANA GRANDE DE BOYÁ',
            self::DM_SABANA_GRANDE_DE_BOYA => 'SABANA GRANDE DE BOYÁ (D. M.).',
            self::DM_GONZALO => 'GONZALO (D. M.).',
            self::DM_MAJAGUAL => 'MAJAGUAL (D. M.).',
            self::MUN_YAMASA => 'MUNICIPIO YAMASÁ',
            self::DM_LOS_BOTADOS => 'LOS BOTADOS (D. M.).',
            self::DM_MAMA_TINGO => 'MAMÁ TINGÓ (D. M.).',
            self::MUN_PERALVILLO => 'MUNICIPIO PERALVILLO',
            self::DM_PERALVILLO => 'PERALVILLO (D. M.).',
        ],
        Province::HATO_MAYOR => [
            self::MUN_HATO_MAYOR => 'MUNICIPIO HATO MAYOR',
            self::DM_HATO_MAYOR => 'HATO MAYOR (D. M.).',
            self::DM_YERBA_BUENA => 'YERBA BUENA (D. M.).',
            self::DM_MATA_PALACIO => 'MATA PALACIO (D. M.).',
            self::DM_GUAYABO_DULCE => 'GUAYABO DULCE (D. M.).',
            self::MUN_SABANA_DE_LA_MAR => 'MUNICIPIO SABANA DE LA MAR',
            self::DM_SABANA_DE_LA_MAR => 'SABANA DE LA MAR (D. M.).',
            self::DM_ELUPINA_CORDERO_DE_LAS_CANITAS => 'ELUPINA CORDERO DE LAS CAÑITAS (D. M.).',
            self::MUN_EL_VALLE => 'MUNICIPIO EL VALLE',
            self::DM_EL_VALLE => 'EL VALLE (D. M.).',
        ],
        Province::SAN_JOSE_DE_OCOA => [
            self::MUN_SAN_JOSE_DE_OCOA => 'MUNICIPIO SAN JOSÉ DE OCOA',
            self::DM_SAN_JOSE_DE_OCOA => 'SAN JOSÉ DE OCOA (D. M.).',
            self::DM_LA_CIENAGA_SAN_JOSE_DE_OCOA => 'LA CIÉNAGA (D. M.).',
            self::DM_NIZAO_LAS_AUYAMAS => 'NIZAO - LAS AUYAMAS (D. M.).',
            self::DM_EL_PINAR => 'EL PINAR (D. M.).',
            self::DM_EL_NARANJAL => 'EL NARANJAL (D. M.).',
            self::MUN_SABANA_LARGA => 'MUNICIPIO SABANA LARGA',
            self::DM_SABANA_LARGA => 'SABANA LARGA (D. M.).',
            self::MUN_RANCHO_ARRIBA => 'MUNICIPIO RANCHO ARRIBA',
            self::DM_RANCHO_ARRIBA => 'RANCHO ARRIBA (D. M.).',
        ],
        Province::SANTO_DOMINGO => [
            self::MUN_SANTO_DOMINGO_ESTE => 'MUNICIPIO SANTO DOMINGO ESTE',
            self::DM_SANTO_DOMINGO_ESTE => 'SANTO DOMINGO ESTE (D. M.).',
            self::DM_SAN_LUIS => 'SAN LUIS (D. M.).',
            self::MUN_SANTO_DOMINGO_OESTE => 'MUNICIPIO SANTO DOMINGO OESTE',
            self::DM_SANTO_DOMINGO_OESTE => 'SANTO DOMINGO OESTE (D. M.).',
            self::MUN_SANTO_DOMINGO_NORTE => 'MUNICIPIO SANTO DOMINGO NORTE',
            self::DM_SANTO_DOMINGO_NORTE => 'SANTO DOMINGO NORTE (D. M.).',
            self::DM_LA_VICTORIA => 'LA VICTORIA (D. M.).',
            self::MUN_BOCA_CHICA => 'MUNICIPIO BOCA CHICA',
            self::DM_BOCA_CHICA => 'BOCA CHICA (D. M.).',
            self::DM_LA_CALETA => 'LA CALETA (D. M.).',
            self::MUN_SAN_ANTONIO_DE_GUERRA => 'MUNICIPIO SAN ANTONIO DE GUERRA',
            self::DM_SAN_ANTONIO_DE_GUERRA => 'SAN ANTONIO DE GUERRA (D. M.).',
            self::DM_HATO_VIEJO => 'HATO VIEJO (D. M.).',
            self::MUN_LOS_ALCARRIZOS => 'MUNICIPIO LOS ALCARRIZOS',
            self::DM_LOS_ALCARRIZOS => 'LOS ALCARRIZOS (D. M.).',
            self::DM_PALMAREJO_VILLA_LINDA => 'PALMAREJO-VILLA LINDA (D. M.).',
            self::DM_PANTOJA => 'PANTOJA (D. M.).',
            self::MUN_PEDRO_BRAND => 'MUNICIPIO PEDRO BRAND',
            self::DM_PEDRO_BRAND => 'PEDRO BRAND (D. M.).',
            self::DM_LA_GUAYIGA => 'LA GUÁYIGA (D. M.).',
            self::DM_LA_CUABA => 'LA CUABA (D. M.).',
        ]
    ];

    private static $flatMunicipalityMap = null;

    public static function listForFormBuilder(string $provinceCode): ?array
    {
        if (!Province::exists($provinceCode)) {
            return null;
        }

        $list = [];
        foreach (self::$map[$provinceCode] as $code => $name) {
            $list[$name] = $code;
        }
        return $list;
    }

    public static function getName(string $code): ?string
    {
        if (self::$flatMunicipalityMap === null) {
            self::buildFlatMap();
        }

        return self::$flatMunicipalityMap[$code]['name'] ?? null;
    }

    public static function getProvinceCodeForMunicipality(string $code): ?string
    {
        if (self::$flatMunicipalityMap === null) {
            self::buildFlatMap();
        }

        return self::$flatMunicipalityMap[$code]['provinceCode'] ?? null;
    }

    public static function exists(string $code): bool
    {
        if (self::$flatMunicipalityMap === null) {
            self::buildFlatMap();
        }

        return array_key_exists($code, self::$flatMunicipalityMap);
    }

    private static function buildFlatMap(): void
    {
        self::$flatMunicipalityMap = [];
        foreach (self::$map as $provinceCode => $municipalities) {
            foreach ($municipalities as $municipalityCode => $municipalityName) {
                self::$flatMunicipalityMap[$municipalityCode] = [
                    'name' => $municipalityName,
                    'provinceCode' => $provinceCode,
                ];
            }
        }
    }
}